### ISSUE TITLE
[Suggestion] Add Root URL for published resources (CSS/JS)

### ISSUE THREAD

**Issue by DarkGhostHunter** [drone/drone-ui#306] opened 2019-08-22 21:57 UTC
When running under Docker/k8s, all resources (CSS and JS) are retrieved using the root server address:

    https://wever.com/js/app.da7a5734.js

On servers where the use of subdomains is not possible, one solution is to use `traefik` to host services under a prefix:

    https://wever.com/drone

The problem is that, while using this, the UI still request the resources from the root server

    https://wever.com/drone/js/app.da7a5734.js // This should be good

    https://wever.com/js/app.da7a5734.js // but we receive this

It would be awesome to have a `DRONE_ROOT_URL` to put a root prefix to the resources requested by the UI.

**Comment by bradrydzewski** [comment] 2019-08-22 22:07
Unfortunately this is not as simple as a website update. It requires a number of server changes to include subpath in things like webhooks, statuses, etc.  I am sorry to say we have already decided supporting subpaths is out of scope for the project. We are therefore unable to accommodate your request.  (duplicate of https://github.com/drone/drone/issues/475)

**Closed** 2019-08-31 20:39 UTC
