### ISSUE TITLE
Possibility to cancel queued builds

### ISSUE THREAD

**Issue by zzhelyazkov** [drone/drone-ui#129] opened 2017-07-18 16:24 UTC
It's annoying having to wait other builds to be able to cancel the builds (from UI) you want to skip, any chance we could have that implemented? :P

**Comment by bradrydzewski** [comment] 2017-07-18 16:43
duplicate of https://github.com/drone/drone/issues/1284

**Closed by bradrydzewski** 2017-07-18 16:43 UTC

**Comment by tonglil** [comment] 2018-01-10 00:46
@bradrydzewski not to beat a dead horse, but I think this issue should be closed and #1284 re-opened (or a new issue created).

Happy to discuss more.

Just FYI this is different from https://github.com/drone/drone/issues/1980.

**Comment by ylecuyer** [comment] 2018-02-06 15:12
Sure this issue should be considered and reopened for a quickfix
