### ISSUE TITLE
Safari does not support EventSource with http2

### ISSUE THREAD

**Issue by jmccann** [drone/drone-ui#169] opened 2017-09-18 21:53 UTC
When connecting to Drone UI with Safari, the drone server process will have high utilization and may be leaking memory.

This seems due to safari causing very frequent open/close connections from sse?

Working fine with Chrome and Firefox.

Please read linked topic for more info: https://discourse.drone.io/t/drone-server-hangs-from-event-stream/710/7

**Comment by bradrydzewski** [comment] 2017-09-19 05:10
ok ... this is really screwed up. I can repeat this by adding the following directly to the developer console in safari.

```
var events = new EventSource("/stream/events");
```

I can only seem to reproduce this when I'm using __https__. I cannot reproduce this when using http. I have no clue why, and google search did not return anything useful.

I tested with a polyfill but the results were the same:
https://raw.githubusercontent.com/Yaffle/EventSource/master/src/eventsource.min.js

😢

**Comment by bradrydzewski** [comment] 2017-09-19 19:07
I have isolated the issue and am now quite certain it is a bug when using EventSource in Safari with http2. I created a small test server and tested http1 and http2 protocols, and confirmed it worked as expected when using http1, but failed when using http2

```diff
		httpServer := &http.Server{
			Addr: ":443",
			TLSConfig: &tls.Config{
				GetCertificate: manager.GetCertificate,
-				NextProtos:     []string{"h2", "http/1.1"},
+				NextProtos:     []string{"http/1.1"},
			},
		}
```

I think the next step is to test this out in Safari 11 beta and Safari TP to see if this issue has been resolved. If no, we need to report to the Safari or Webkit team.

I am actively looking for workarounds that we can implement within Go to prevent http2 upgrades for the Safari browser. Relevant thread:
https://stackoverflow.com/questions/46292945/safari-server-sent-event-sse-infinte-loop

I also have an open StackOverflow issue:
https://groups.google.com/forum/#!topic/golang-nuts/fBR6kBmZY3U

Worst case scenario is that we block EventSource requests for Safari and we have to display an error message in the user interface indicating Safari is not supported, with a link to a webkit bug. Let's hope we can find a better approach, though :(

**Comment by jmccann** [comment] 2017-09-19 21:47
Tested Safari 11 (Version 11.0 (12604.1.38.1.7)) and still saw this issue.

**Comment by bradrydzewski** [comment] 2017-09-19 22:47
ok, https://github.com/drone/drone/commit/ae51e9d1b987f9086cbc65e694f06759bc62e743 removes support for http2. We can create an issue with the webkit folks and see if we can help get this resolved.

**Comment by bradrydzewski** [comment] 2017-09-19 22:47
I am going to close this for now as resolved.

**Closed by bradrydzewski** 2017-09-19 22:47 UTC
