### ISSUE TITLE
Pipeline collapse doesn't work.

### ISSUE THREAD

**Issue by cicerocomp** [drone/drone-ui#110] opened 2017-05-05 18:56 UTC
Test: http://beta.drone.io/drone/drone-ui/157
![may-05-2017 15-52-25](https://cloud.githubusercontent.com/assets/755111/25759928/f0ce411c-31aa-11e7-8093-d790a396c46f.gif)

**Comment by bradrydzewski** [comment] 2017-05-05 19:21
duplicate of https://github.com/drone/drone-ui/issues/102

**Closed by bradrydzewski** 2017-05-05 19:21 UTC
