### ISSUE TITLE
Getting unauthorized repsonse on showing token

### ISSUE THREAD

**Issue by tboerger** [drone/drone-ui#35] opened 2016-07-10 19:43 UTC
If I want to see my token I'm just getting an `Unauthorized` error from the API.

**Comment by bradrydzewski** [comment] 2016-07-10 19:46
duplicate of https://github.com/drone/drone-ui/issues/26 which prevents any non-GET calls from working properly

**Closed by bradrydzewski** 2016-07-10 19:46 UTC

**Comment by tboerger** [comment] 2016-07-10 19:49
Good catch :D
