### ISSUE TITLE
Project list is not visible on mobile (v0.6)

### ISSUE THREAD

**Issue by cyberb** [drone/drone-ui#117] opened 2017-05-20 09:27 UTC
Unable to select a project on mobile:

<img src="https://cloud.githubusercontent.com/assets/885528/26274606/5a27d948-3d45-11e7-9096-4967e7b8151d.png" width="300px">

I have them:
<img src="https://cloud.githubusercontent.com/assets/885528/26274670/bea3825e-3d46-11e7-93af-e4c89db2040d.png" width="300px">

**Comment by bradrydzewski** [comment] 2017-05-20 09:30
duplicate of https://github.com/drone/drone-ui/issues/27

**Closed by bradrydzewski** 2017-05-20 09:30 UTC
