### ISSUE TITLE
visualize agent in user interface

### ISSUE THREAD

**Issue by strk** [drone/drone-ui#285] opened 2019-05-02 14:20 UTC
It is useful to know which agent is picking which build.
See https://github.com/drone/drone/issues/1496#issuecomment-316764279

**Comment by tboerger** [comment] 2019-05-03 00:21
Duplicate of https://github.com/drone/drone-ui/issues/135

**Comment by bradrydzewski** [comment] 2019-06-23 05:06
closing a duplicate of #135

**Closed by bradrydzewski** 2019-06-23 05:06 UTC
