### ISSUE TITLE
Guest users get error message, adjust initialization logic

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#238] opened 2018-12-19 18:27 UTC
I will try to submit a patch for these today. There are two adjustments that we can make to the initialization logic to fix issues that guest / anonymous users are experiencing.

First, data should always be streamed, even if the user is not authenticated. Otherwise the user will not receive live updates if they are not logged in.

```diff
+store.dispatch("streamEvents")

store.dispatch('fetchViewer').then(() => {
  // once the attempt to ascertain the currently
  // authenticated user completes, load the application.
  new Vue({
    i18n,
    router,
    store,
    render: h => h(App)
  }).$mount("#app");

  store
    .dispatch("fetchReposLatest")
-    .then(() => store.dispatch("streamEvents"))
    .catch(error => {
      const message = `Can't enable realtime updates. Error: ${JSON.stringify(error)}`;
      store.dispatch("showNotification", { message });
    });
});
```

Second, we should only fetch the latest repository list if the user is authenticated. Otherwise the guest user always gets an error message.

```diff
store.dispatch('fetchViewer').then(() => {
  // once the attempt to ascertain the currently
  // authenticated user completes, load the application.
  new Vue({
    i18n,
    router,
    store,
    render: h => h(App)
  }).$mount("#app");

+ if (store.user.data.login) { // with this work? not sure
  store
    .dispatch("fetchReposLatest")
    .catch(error => {
      const message = `Can't enable realtime updates. Error: ${JSON.stringify(error)}`;
      store.dispatch("showNotification", { message });
    });
+ }
});
```

**Comment by proAlexandr** [comment] 2018-12-24 09:47
Hi, @bradrydzewski 
I have tried to fix it, but I noticed a problem. Each request to the backend from a guest user (an unauthenticated user) ends with an error "{"message": "Unauthorized"}". So the guest can't fetch even repository data (for example /api/repos/proAlexandr/hello-world).
Let's we firstly allow the guest to receive repo data and then I will fix streaming issue?

**Comment by bradrydzewski** [comment] 2018-12-27 14:54
@proAlexandr `https://cloud.drone.io/proAlexandr/hello-world` was marked as private in the Settings page, so it is expected that a guest user sees a Not Found error.

**Comment by proAlexandr** [comment] 2018-12-28 06:09
@bradrydzewski Sorry, my mistake. I will continue this task today.

**Comment by proAlexandr** [comment] 2019-01-22 08:36
I assume the issue is solved and I can close it.

**Closed by proAlexandr** 2019-01-22 08:36 UTC
Labels: v1.0.0
